In [1]:
import pandas as pd

# some rows contain >7 columns, so we need to ignore those
lines = open("../data/sts-test.csv").read().split("\n")
columns = ['domain','data','type','score','correlation','text_1','text_2']
df = pd.DataFrame([dict(zip(columns, line.split("\t")[:7])) for line in lines[:-1]])
df

,domain,data,type,score,correlation,text_1,text_2
0,main-captions,MSRvid,2012test,0024,2.500,A girl is styling her hair.,A girl is brushing her hair.
1,main-captions,MSRvid,2012test,0033,3.600,A group of men play soccer on the beach.,A group of boys are playing soccer on the beach.
2,main-captions,MSRvid,2012test,0045,5.000,One woman is measuring another woman's ankle.,A woman measures another woman's ankle.
3,main-captions,MSRvid,2012test,0063,4.200,A man is cutting up a cucumber.,A man is slicing a cucumber.
4,main-captions,MSRvid,2012test,0066,1.500,A man is playing a harp.,A man is playing a keyboard.
...,...,...,...,...,...,...,...
1374,main-news,headlines,2016,1354,0,"Philippines, Canada pledge to further boost re...",Philippines saves 100 after ferry sinks
1375,main-news,headlines,2016,1360,1,Israel bars Palestinians from Jerusalem's Old ...,"Two-state solution between Palestinians, Israe..."
1376,main-news,headlines,2016,1368,1,How much do you know about Secret Service?,Lawmakers from both sides express outrage at S...
1377,main-news,headlines,2016,1420,0,Obama Struggles to Soothe Saudi Fears As Iran ...,Myanmar Struggles to Finalize Voter Lists for ...
1378,main-news,headlines,2016,1432,0,South Korea declares end to MERS outbreak,North Korea Delegation Meets With South Korean...

In [2]:
from tqdm.contrib.concurrent import thread_map
import mtranslate

translate = lambda text: mtranslate.translate(text, "id", "en")
df["text_1"] = thread_map(translate, df["text_1"])
df["text_2"] = thread_map(translate, df["text_2"])

  0%|          | 0/1379 [00:00<?, ?it/s]

  0%|          | 0/1379 [00:00<?, ?it/s]

In [3]:
df

,domain,data,type,score,correlation,text_1,text_2
0,main-captions,MSRvid,2012test,0024,2.500,Seorang gadis sedang menata rambutnya.,Seorang gadis sedang menyisir rambutnya.
1,main-captions,MSRvid,2012test,0033,3.600,Sekelompok pria bermain sepak bola di pantai.,Sekelompok anak laki-laki sedang bermain sepak...
2,main-captions,MSRvid,2012test,0045,5.000,Seorang wanita mengukur pergelangan kaki wanit...,Seorang wanita mengukur pergelangan kaki wanit...
3,main-captions,MSRvid,2012test,0063,4.200,Seorang pria sedang memotong mentimun.,Seorang pria sedang mengiris mentimun.
4,main-captions,MSRvid,2012test,0066,1.500,Seorang pria sedang memainkan harpa.,Seorang pria sedang memainkan keyboard.
...,...,...,...,...,...,...,...
1374,main-news,headlines,2016,1354,0,"Filipina, Kanada berjanji untuk lebih meningka...",Filipina menghemat 100 setelah feri tenggelam
1375,main-news,headlines,2016,1360,1,Israel melarang warga Palestina dari Kota Tua ...,"Solusi dua negara antara Palestina, Israel pai..."
1376,main-news,headlines,2016,1368,1,Berapa banyak yang Anda ketahui tentang Dinas ...,Anggota parlemen dari kedua belah pihak mengun...
1377,main-news,headlines,2016,1420,0,Obama Berjuang untuk Menenangkan Ketakutan Sau...,Myanmar Berjuang untuk Menyelesaikan Daftar Pe...
1378,main-news,headlines,2016,1432,0,Korea Selatan mengumumkan berakhirnya wabah MERS,Delegasi Korea Utara Bertemu dengan Pejabat Ko...

In [4]:
df.to_csv("../data/sts-test-ind.csv", index=False)

In [5]:
from datasets import Dataset

dataset = Dataset.from_pandas(df, split="test")
dataset.push_to_hub("LazarusNLP/stsb_mt_id", private=True)

Pushing dataset shards to the dataset hub:   0%|          | 0/1 [00:00<?, ?it/s]